service: react-fastapi-service

provider:
  name: aws
  ecr:
    images:
      react-fastapi-image:
        path: ./  # Directory containing your Dockerfile
        platform: linux/amd64

functions:
  reactFastapiFunction:
    image:
      name: react-fastapi-image
    url: true
